version: "3.1"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
